## Numpy
- 선형대수, 행렬 수치연산과 관련된 라이브러리리

In [1]:
pip install numpy

In [31]:
import streamlit as st

print(st.__version__)

1.29.0


In [4]:
import numpy as np # Numpy 라이브러리 불러오기

print(np.__version__)

1.24.3


In [5]:
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [6]:
arr1 = np.array(num1)
arr2 = np.array(num2)

In [7]:
arr1

array([1, 2, 3, 4])

In [8]:
arr2

array([3, 4, 5, 6])

In [9]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [10]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [13]:
a1.dtype # Python int # Numpy int8, int6, int 32, int64

dtype('int32')

In [17]:
np.array([0.5, 2, 0.01, 8]).dtype

dtype('float64')

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10) # 1차원 배열, 2차원 또는 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [36]:
b2 = np.arange(5)
b2.shape

(5,)

In [39]:
# 범위의 시작과 끝 정하기 배열 생성
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [41]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [51]:
# 단위행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr_I.shape

(3, 3)

In [56]:
np.array(['1.5', '0.62']) # 데이터 형변환

array(['1.5', '0.62'], dtype='<U4')

In [60]:
# astype() # pandas에서도 사용 가능
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [62]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

In [64]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [66]:
# p. 224
# 난수란 무작위로 추출한 수를 의미함

np.random.rand(2, 3) # 2x3 배열로 생성 # rand는 0~1 사이의 실수 난수를 갖음

array([[0.47292595, 0.57392055, 0.57216566],
       [0.07749174, 0.95906272, 0.18439392]])

In [69]:
np.random.randint(1, 100, 10) # randit는 1과 100사이의 정수 10개 추출로 설정했음

array([25, 11, 40, 18, 25,  2, 29, 56, 72, 56])

In [116]:
# 로또번호 생성하기
import random

lotto = random.sample(range(1, 46), 6)
print("로또번호: {}".format(lotto)) # print("로또번호는 :", lotto,"입니다")

로또번호: [35, 18, 39, 45, 11, 44]


## 배열의 연산
- p.225

In [120]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


## 비교연산 

In [122]:
arr1 > 20

array([False, False,  True,  True])

## 통계 연산
- Numpy, 합, 평균, 표준편차, 최솟값, 최댓값, 누적합, 누적곱 메서드가 존재한다.
 +기술통계량 (Descriptive Statistics) : 현재 데이터 상태를 표현(묘사)한다. 
- 통계 : 평균이 전부다! (Mean is everything)

In [134]:
arr3 = np.arange(5)
arr

array(['1.5', '0.62'], dtype='<U4')

In [126]:
arr3.sum()

10

In [129]:
arr3.mean()

2.0

In [132]:
arr3.var() # 분산

2.0

In [131]:
arr3.std() # 표준편차

1.4142135623730951

## 누적합과 누적곱
- cumsum(): 누적합
- cumprod(): 누적곱

In [136]:
arr = np.arange(1, 5)
arr4

array([0, 1, 2, 3, 4])

## 행렬연산
- 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원
- p229, 행렬곱, 전치행렬, 역행렬, 행렬식 사용 예시

In [139]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [145]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [147]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [149]:
A.transpose() # 전치행렬

array([[0, 2],
       [1, 3]])

In [151]:
np.linalg.inv(A) # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## 배열의 인덱싱과 슬라이싱(p.230)
- string, list, tuple과 동일한 방법으로 접근 

In [153]:
a1 = np.array([0,10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [156]:
a1[4]

40

In [162]:
# 50을 70으로 변경하고 싶음
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [165]:
# 리스트를 통해서 추출
a1[[0, 2, 4]]

array([ 0, 20, 40])

In [167]:
idx_list = [0, 2, 4]
a1[idx_list]

array([ 0, 20, 40])

In [168]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [170]:
a2[0,1]

20

In [172]:
a2[2,2]

90

In [174]:
# 90을 95로 변경
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [184]:
a2[2,2] = 95
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [ 1,  2, 95]])

In [185]:
a2[0]

array([1, 2, 3])

In [187]:
a2[0] = [1, 2, 3]
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [ 1,  2, 95]])

In [190]:
a2[0] = np.array([1, 2, 3]) # 정석
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [ 1,  2, 95]])

In [191]:
a2[0] = np.array([1, 2, 3,4]) # 에러! 배열의 사이즈 안 맞음
a2

ValueError: could not broadcast input array from shape (4,) into shape (3,)

- 2차원 배열의 행과 열 위치 지정해서 원소 추출
 +(행의 위치1, 열의 위치1)/(행의 위치2, 열의 위치2)

In [194]:
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [ 1,  2, 95]])

In [193]:
a2[[0,2],[0,1]]

array([1, 2])

In [197]:
a2[[0,2], [0,1]]

array([1, 2])

## 베열의 조건문
- pandas 문법과 유사

In [203]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [204]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [206]:
a[a>3]

array([4, 5, 6])

In [208]:
a % 2 == 0 

array([False,  True, False,  True, False,  True])

## 배열의 슬라이싱

In [210]:
# p.234
b1 = np.array([0,1,2,3,4,5])
b1[1:4]

array([1, 2, 3])

In [212]:
b1[:3]

array([0, 1, 2])

In [214]:
b1[2:]

array([2, 3, 4, 5])

In [216]:
b1[0:4:2]

array([0, 2])

In [218]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [220]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [223]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [225]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [227]:
b2[1:,1:]

array([[50, 60],
       [80, 90]])

In [233]:
b2[1][1:3]

array([50, 60])

## NumPy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [237]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr < 5, arr, arr*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [238]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [240]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2미만일 때는 100을 더해라
# 5초과일 때는 곱하기 2를 하라

# 조건식과 대응되는 결과를 리스트로 만들기
cond_list = [arr>5, arr<2]
choice_list = [arr*2, arr +100]

np.select(cond_list, choice_list, default=arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])